#!/bin/bash

echo "🧹 Clearing browser cache and service workers..."
echo ""
echo "Please follow these steps in your browser:"
echo ""
echo "1. Open Chrome DevTools (F12 or Cmd+Option+I on Mac)"
echo "2. Go to the 'Application' tab"
echo "3. In the left sidebar, find 'Storage'"
echo "4. Click 'Clear site data' button"
echo ""
echo "Alternative method:"
echo "1. Open Chrome DevTools"
echo "2. Right-click the refresh button"
echo "3. Select 'Empty Cache and Hard Reload'"
echo ""
echo "For Service Workers:"
echo "1. In DevTools > Application > Service Workers"
echo "2. Click 'Unregister' for any workers listed"
echo ""
echo "Or visit: chrome://settings/content/all and delete data for localhost:3000"
echo ""
echo "✅ After clearing, refresh the page and the WebSocket errors should stop."