version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # API port
      - "3000:3000"  # Demo UI port
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-1106-preview}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_ORCHESTRATOR_MODEL=${CLAUDE_ORCHESTRATOR_MODEL:-claude-3-opus-20240229}
      - CLAUDE_WORKER_MODEL=${CLAUDE_WORKER_MODEL:-claude-3-sonnet-20240229}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./logs:/app/logs
    networks:
      - privacy-llm-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - privacy-llm-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  privacy-llm-network:
    driver: bridge